# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Octo's training
description: The greatest achievements are the result of shared knowledge

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, app.json, Gemfile.lock]

collections:
  training:
    output: true

markdown: kramdown
